mine
ZeyadAbdullah679/cost-of-living pull request #2
Opened 2023-02-24 18:33 UTC by Menna120

give me your openion in what i have done

2023-02-25 16:40 UTC, 3105731 commented
jghcgx

2023-02-25 18:25 UTC, ZeyadAbdullah679 commented on src/main/kotlin/interactor/Consumption.kt
> +            && city.dataQuality
He didn't mention to check the dataQuality in task 10, so you shouldn't exclude values according to dataQuality

2023-02-25 18:26 UTC, ZeyadAbdullah679 commented on src/main/kotlin/interactor/Consumption.kt
> +    fun execute(): String {
function should return CityEntity not the name of the city as mentioned

2023-02-25 18:30 UTC, ZeyadAbdullah679 commented on src/main/kotlin/interactor/Consumption.kt
> +            &&city.foodPrices.loafOfFreshWhiteBread500g != null
line 37, 38, 39, 40
he didn't mention any of this I know that is also from consumptions, but you should be strict with which asked to check in task

2023-02-25 18:32 UTC, ZeyadAbdullah679 commented on src/main/kotlin/interactor/Consumption.kt
> +private fun servicesCoast(city:CityEntity):Float{
servicesCost function all calculations is not mentioned in problem.

2023-02-26 21:57 UTC, ZeyadAbdullah679 commented on src/main/kotlin/interactor/Consumption.kt
> +            .forEach {
line 13 to the function return in line 20
try to make the code more cleaner and readable think in another way you can do the same thing

2023-02-26 22:00 UTC, ZeyadAbdullah679 commented on src/main/kotlin/interactor/Consumption.kt
>              -city.realEstatesPrices.apartment3BedroomsOutsideOfCentre!!
line 37 you have apartments that inside the city and outside the city you should get the minimum amount between them it is just a logic doesn't mean something to me just to make you aware only..

2023-02-26 22:03 UTC, ZeyadAbdullah679 commented on src/main/kotlin/Main.kt
> +    print(Consumption(dataSource).execute())
You did it Annapolis is right!

Congratulations 👏

2023-02-26 22:05 UTC, ZeyadAbdullah679 requested changes
You did well, now try to clean your code using only equal operator for return in execute() do your best!
I mean like this fun execute()=something

2023-02-28 18:49 UTC, closed without merging